"""Daily pipeline artifact paths and lifecycle status constants."""

from __future__ import annotations

from pathlib import Path

PHASE = "DAILY-PIPELINE-1"
DEFAULT_TIMEZONE = "Europe/Vienna"

PIPELINE_ARTIFACTS_ROOT = Path("artifacts") / "daily_pipeline"
DAILY_REPORTS_DIR = Path("reports") / "owner" / "daily"
REPORT_INDEX_PATH = PIPELINE_ARTIFACTS_ROOT / "report_index.json"
FORENSICS_DIR = Path("data") / "shadow" / "daily_pipeline_forensics"

# Canonical terminal lifecycle statuses (every fixture ends in exactly one)
PREDICTED_AND_FROZEN = "PREDICTED_AND_FROZEN"
ALREADY_FROZEN_IDEMPOTENT_REUSE = "ALREADY_FROZEN_IDEMPOTENT_REUSE"
NO_BET_LOW_DATA_QUALITY = "NO_BET_LOW_DATA_QUALITY"
BLOCKED_STALE_ODDS = "BLOCKED_STALE_ODDS"
BLOCKED_MISSING_ODDS = "BLOCKED_MISSING_ODDS"
BLOCKED_UNSUPPORTED_COMPETITION = "BLOCKED_UNSUPPORTED_COMPETITION"
BLOCKED_FRIENDLY = "BLOCKED_FRIENDLY"
BLOCKED_MISSING_DEPENDENCY = "BLOCKED_MISSING_DEPENDENCY"
BLOCKED_POST_KICKOFF = "BLOCKED_POST_KICKOFF"
BLOCKED_MAPPING_CONFLICT = "BLOCKED_MAPPING_CONFLICT"
BLOCKED_PROVIDER_FAILURE = "BLOCKED_PROVIDER_FAILURE"
MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

ALL_LIFECYCLE_STATUSES = frozenset(
    {
        PREDICTED_AND_FROZEN,
        ALREADY_FROZEN_IDEMPOTENT_REUSE,
        NO_BET_LOW_DATA_QUALITY,
        BLOCKED_STALE_ODDS,
        BLOCKED_MISSING_ODDS,
        BLOCKED_UNSUPPORTED_COMPETITION,
        BLOCKED_FRIENDLY,
        BLOCKED_MISSING_DEPENDENCY,
        BLOCKED_POST_KICKOFF,
        BLOCKED_MAPPING_CONFLICT,
        BLOCKED_PROVIDER_FAILURE,
        MANUAL_REVIEW_REQUIRED,
    }
)

PIPELINE_COMPLETE = "DAILY_PIPELINE_COMPLETE"
PIPELINE_PARTIAL = "DAILY_PIPELINE_PARTIAL"
PIPELINE_BLOCKED = "DAILY_PIPELINE_BLOCKED"
PIPELINE_NO_FIXTURES = "DAILY_PIPELINE_NO_FIXTURES"


def day_dir(report_date: str) -> Path:
    """YYYY-MM-DD artifact directory."""
    return PIPELINE_ARTIFACTS_ROOT / report_date
