"""ECSE probability tail forensics — research constants."""

from __future__ import annotations

PHASE = "ECSE-PROBABILITY-TAIL-FORENSICS-1"
SHADOW_ONLY = True
PUBLIC_PUBLISH = False
ARTIFACT_SUBDIR = "ecse_tail_forensics"

PROMOTION_MIN_FIXTURES = 10_000
PROMOTION_MIN_SEGMENT = 500
PROMOTION_TOP5_LIFT_PP = 2.0
PROMOTION_TOP3_MAX_DEGRADATION_PP = 0.5

TIME_SPLIT_TRAIN_END = "2024-01-01"
TIME_SPLIT_VALIDATE_START = "2024-01-01"

METHOD_CANONICAL_POISSON = "canonical_poisson"
METHOD_DIXON_COLES = "dixon_coles"
METHOD_BIVARIATE_POISSON = "bivariate_poisson"
METHOD_NEGATIVE_BINOMIAL = "negative_binomial"
METHOD_ZERO_INFLATED = "zero_inflated"
METHOD_LEAGUE_VARIANCE = "league_variance"
METHOD_TAIL_TEMPERATURE = "tail_temperature"
METHOD_UNDERDOG_FLOOR = "underdog_floor"
METHOD_BTTS_CONSISTENCY = "btts_consistency"
METHOD_OU_CONSISTENCY = "ou_consistency"
METHOD_HYBRID_TAIL = "hybrid_tail"

ALL_METHODS = (
    METHOD_CANONICAL_POISSON,
    METHOD_DIXON_COLES,
    METHOD_BIVARIATE_POISSON,
    METHOD_NEGATIVE_BINOMIAL,
    METHOD_LEAGUE_VARIANCE,
    METHOD_TAIL_TEMPERATURE,
    METHOD_UNDERDOG_FLOOR,
    METHOD_BTTS_CONSISTENCY,
    METHOD_HYBRID_TAIL,
)

UNSUPPORTED_METHODS = frozenset({METHOD_ZERO_INFLATED})

FINAL_STATUS_VALUES = frozenset(
    {
        "ECSE_TAIL_CORRECTION_IMPROVES_TOP5",
        "ECSE_SEGMENT_SPECIFIC_TAIL_LIFT",
        "ECSE_NO_TAIL_ADVANTAGE",
        "ECSE_MORE_DATA_REQUIRED",
        "ECSE_TAIL_VALIDATION_FAILED",
    }
)

LOW_SCORE_LINES = frozenset({"0-0", "1-0", "0-1", "1-1"})
MEDIUM_SCORE_LINES = frozenset(
    {"2-0", "0-2", "2-1", "1-2", "2-2", "3-0", "0-3"}
)
HIGH_SCORE_TAIL_LINES = frozenset(
    {
        "3-1", "1-3", "3-2", "2-3", "4-0", "0-4", "4-1", "1-4",
        "4-2", "2-4", "4-3", "3-4",
    }
)

FORENSIC_FIXTURE_DJURGARDEN = 1494202
FORENSIC_FIXTURE_KA_IA = 1508804
