"""Correct Score odds availability statuses (owner pipeline enrichment)."""

CS_ODDS_AVAILABLE = "CS_ODDS_AVAILABLE"
CS_ODDS_PARTIAL = "CS_ODDS_PARTIAL"
CS_ODDS_UNAVAILABLE = "CS_ODDS_UNAVAILABLE"
CS_ODDS_PROVIDER_BLOCKED = "CS_ODDS_PROVIDER_BLOCKED"
CS_ODDS_MARKET_UNSUPPORTED = "CS_ODDS_MARKET_UNSUPPORTED"
CS_ODDS_STALE = "CS_ODDS_STALE"
CS_ODDS_MAPPING_CONFLICT = "CS_ODDS_MAPPING_CONFLICT"

CS_ODDS_STATUSES = {
    CS_ODDS_AVAILABLE,
    CS_ODDS_PARTIAL,
    CS_ODDS_UNAVAILABLE,
    CS_ODDS_PROVIDER_BLOCKED,
    CS_ODDS_MARKET_UNSUPPORTED,
    CS_ODDS_STALE,
    CS_ODDS_MAPPING_CONFLICT,
}

FINAL_PHASE_STATUSES = {
    "CORRECT_SCORE_ODDS_INGESTION_COMPLETE",
    "CORRECT_SCORE_ODDS_FORWARD_COLLECTION_ACTIVE",
    "CORRECT_SCORE_ODDS_MANUAL_IMPORT_REQUIRED",
    "CORRECT_SCORE_ODDS_PROVIDER_NOT_AVAILABLE",
    "TWO_FIXTURE_PORTFOLIO_REAL_ODDS_EDGE_PROVEN",
    "TWO_FIXTURE_PORTFOLIO_REAL_ODDS_NO_EDGE",
    "TWO_FIXTURE_PORTFOLIO_MORE_FORWARD_DATA_REQUIRED",
    "CORRECT_SCORE_ODDS_VALIDATION_FAILED",
}

CANONICAL_MARKET = "CORRECT_SCORE_90_MINUTES"
ANY_OTHER_HOME = "ANY_OTHER_HOME_WIN"
ANY_OTHER_DRAW = "ANY_OTHER_DRAW"
ANY_OTHER_AWAY = "ANY_OTHER_AWAY_WIN"
