"""NEXT_15_STRONGEST_1X2_SELECTION — research ranking over upcoming fixtures."""

PROGRAM = "NEXT_15_STRONGEST_1X2_SELECTION"
STATUS_READY = "NEXT_15_STRONGEST_1X2_SELECTION_READY"
STATUS_PARTIAL = "NEXT_15_STRONGEST_1X2_SELECTION_PARTIAL_ODDS"
STATUS_EMPTY = "NEXT_15_STRONGEST_1X2_SELECTION_NO_UPCOMING"
