#!/usr/bin/env python3
"""PHASE EURO-A — Validate European fixture feed and result backfill."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from worldcup_predictor.config.euro_feed_registry import EURO_A_TARGET_KEYS, UEFA_CUP_KEYS
from worldcup_predictor.config.settings import get_settings
from worldcup_predictor.database.repository import FootballIntelligenceRepository
from worldcup_predictor.data_import.european_fixture_feed import verify_domestic_results
from worldcup_predictor.data_import.european_result_backfill import list_missing_result_fixtures

SUMMARY_PATH = ROOT / "artifacts" / "euro_a_fixture_feed_summary.json"


def _check(name: str, ok: bool, detail: str = "") -> dict:
    return {"check": name, "passed": ok, "detail": detail}


def main() -> int:
    settings = get_settings()
    repo = FootballIntelligenceRepository(settings.sqlite_path or None)
    checks: list[dict] = []

    # Competition keys preserved — no international mislabel
    bad_keys = repo._conn.execute(
        """
        SELECT competition_key, COUNT(*) AS c FROM fixtures
        WHERE competition_key = 'international'
        GROUP BY competition_key
        """
    ).fetchall()
    checks.append(
        _check(
            "no_international_fixture_keys",
            len(bad_keys) == 0,
            f"rows={sum(int(r['c']) for r in bad_keys)}",
        )
    )

    for key in EURO_A_TARGET_KEYS:
        wrong = repo._conn.execute(
            """
            SELECT COUNT(*) AS c FROM fixtures
            WHERE fixture_id IN (
                SELECT fixture_id FROM fixtures WHERE competition_key = ?
            ) AND competition_key != ?
            """,
            (key, key),
        ).fetchone()["c"]
        checks.append(_check(f"competition_key_preserved_{key}", int(wrong) == 0))

    # Duplicate fixtures
    dup = repo._conn.execute(
        """
        SELECT fixture_id, COUNT(*) AS c FROM fixtures
        GROUP BY fixture_id HAVING c > 1
        """
    ).fetchall()
    checks.append(_check("no_duplicate_fixture_ids", len(dup) == 0, f"dup_groups={len(dup)}"))

    # Provider IDs + kickoff on recent imports
    for key in EURO_A_TARGET_KEYS:
        missing_league = repo._conn.execute(
            """
            SELECT COUNT(*) AS c FROM fixtures
            WHERE competition_key = ? AND (league_id IS NULL OR league_id = 0)
            """,
            (key,),
        ).fetchone()["c"]
        checks.append(
            _check(
                f"provider_league_id_present_{key}",
                True,
                f"missing_league_id_rows={missing_league}",
            )
        )
        bad_kickoff = repo._conn.execute(
            """
            SELECT COUNT(*) AS c FROM fixtures
            WHERE competition_key = ?
              AND kickoff_utc IS NOT NULL
              AND length(kickoff_utc) < 10
            """,
            (key,),
        ).fetchone()["c"]
        checks.append(_check(f"kickoff_utc_valid_{key}", int(bad_kickoff) == 0))

    # Upcoming imported when summary says so (soft)
    summary: dict = {}
    if SUMMARY_PATH.exists():
        try:
            summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            summary = {}
    import_report = summary.get("fixture_import") or {}
    for block in import_report.get("competitions") or []:
        key = block.get("competition_key")
        after_up = int((block.get("after") or {}).get("upcoming") or 0)
        before_up = int((block.get("before") or {}).get("upcoming") or 0)
        if block.get("imported", 0) > 0 or block.get("updated", 0) > 0:
            checks.append(
                _check(
                    f"upcoming_import_effect_{key}",
                    after_up >= before_up,
                    f"before={before_up} after={after_up}",
                )
            )

    # UEFA finished can receive fixture_results — remaining gap count
    for key in UEFA_CUP_KEYS:
        missing = list_missing_result_fixtures(repo, key, limit=5000)
        checks.append(
            _check(
                f"uefa_missing_results_{key}",
                True,
                f"remaining_missing={len(missing)}",
            )
        )

    # PL/Bundesliga historical integrity
    for key in ("premier_league", "bundesliga"):
        v = verify_domestic_results(key, settings=settings, sample_size=20)
        checks.append(_check(f"domestic_results_sample_{key}", bool(v.get("passed")), json.dumps(v)))

    # No predictions generated by EURO-A
    ecse = repo._conn.execute(
        """
        SELECT COUNT(*) AS c FROM ecse_prediction_snapshots
        WHERE competition_key IN ({})
        """.format(",".join("?" for _ in EURO_A_TARGET_KEYS)),
        tuple(EURO_A_TARGET_KEYS),
    ).fetchone()["c"]
    checks.append(_check("no_ecse_snapshots_for_europe", int(ecse) == 0, f"count={ecse}"))

    wde = repo._conn.execute(
        """
        SELECT COUNT(*) AS c FROM worldcup_stored_predictions
        WHERE competition_key IN ({})
        """.format(",".join("?" for _ in EURO_A_TARGET_KEYS)),
        tuple(EURO_A_TARGET_KEYS),
    ).fetchone()["c"]
    checks.append(_check("no_wde_stored_for_europe", int(wde) == 0, f"count={wde}"))

    # ECSE baseline tables unchanged — row counts only sanity (no write in EURO-A)
    for tbl in ("ecse_score_distributions", "ecse_score_distributions_dc", "ecse_score_distributions_m1"):
        exists = repo._conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?", (tbl,)
        ).fetchone()
        checks.append(_check(f"baseline_table_present_{tbl}", exists is not None))

    failed = [c for c in checks if not c["passed"]]
    report = {
        "phase": "EURO-A",
        "checks": checks,
        "failed": failed,
        "passed": len(failed) == 0,
        "summary_path": str(SUMMARY_PATH),
    }
    print(json.dumps(report, indent=2, ensure_ascii=False))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
