"""TRUE_FORWARD_OU25_REGIME_MINING_AND_ECSE_DIRECTION_FILTERING — read-only research."""

PROGRAM = "TRUE_FORWARD_OU25_REGIME_MINING_AND_ECSE_DIRECTION_FILTERING"
STATUS_COMPLETE = "OU25_REGIME_MINING_COMPLETE"
STATUS_PARTIAL_ODDS = "OU25_REGIME_MINING_PARTIAL_ODDS_LIMITED"
STATUS_NO_EDGE = "OU25_NO_ROBUST_EDGE_FOUND"
STATUS_INTEGRITY = "OU25_DATA_INTEGRITY_REVIEW_REQUIRED"
STATUS_FAILED = "OU25_VALIDATION_FAILED"

LABEL_BASELINE = "OU25_RAW_BASELINE"
LABEL_DIAGNOSTIC = "OU25_DIAGNOSTIC_RULE"
LABEL_PROMISING = "OU25_PROMISING_RESEARCH_RULE"
LABEL_SUPPORTED = "OU25_STATISTICALLY_SUPPORTED_RULE"
LABEL_NO_EDGE = "OU25_NO_ROBUST_EDGE_FOUND"

RAW_OU_BASELINE = 0.56
