"""OOD Verifier Counterfactual Research — read-only, no new models."""

PHASE_NAME = "OOD_VERIFIER_COUNTERFACTUAL_RESEARCH"
STATUS_COMPLETE = "OOD_VERIFIER_COUNTERFACTUAL_RESEARCH_COMPLETE"
BASELINE_COMMIT = "28fd217"
LOCKED_METHOD = "cosine"
LOCKED_K = 10
LOCKED_REGIMES = 3

DECISION_BUILD = "BUILD_OOD_VERIFIER"
DECISION_ARCHIVE = "ARCHIVE_SIMILARITY_ENGINE"
