"""Challenger program constants — shadow-only safety flags."""

from __future__ import annotations

from typing import Final

CHALLENGER_ENGINE_MODE: Final = "shadow"
CHALLENGER_IS_SHADOW: Final = True
CHALLENGER_PUBLIC_VISIBLE: Final = False
CHALLENGER_FINAL_DECISION_AUTHORITY: Final = False
CHALLENGER_USER_VISIBLE: Final = False

STATUS_OK = "CHALLENGER_OK"
STATUS_DATA_BLOCKED = "CHALLENGER_DATA_BLOCKED"
STATUS_POST_KICKOFF = "CHALLENGER_POST_KICKOFF_BLOCKED"
STATUS_SCHEMA_MISMATCH = "CHALLENGER_SCHEMA_MISMATCH"
STATUS_FAILED = "CHALLENGER_FAILED"

RECONSTRUCTED_RESEARCH_ONLY = "RECONSTRUCTED_RESEARCH_ONLY"
FROZEN_CANONICAL = "FROZEN_CANONICAL"

CONFLICT_CLASSES = (
    "STRONG_AGREEMENT",
    "MODERATE_AGREEMENT",
    "DIRECTION_CONFLICT",
    "DRAW_CALIBRATION_CONFLICT",
    "TOTAL_GOALS_CONFLICT",
    "GOAL_MARKET_CONFLICT",
    "SCORE_DISTRIBUTION_CONFLICT",
    "SNAPSHOT_PARITY_FAILED",
    "INSUFFICIENT_DATA",
)

# Forward rolling review thresholds (completed paired fixtures)
FORWARD_REVIEW_THRESHOLDS = (25, 50, 100, 250, 500)

PROMOTION_DECISIONS = (
    "CHALLENGER_REJECTED",
    "CHALLENGER_MORE_DATA_REQUIRED",
    "CHALLENGER_DOMAIN_LIMITED_RESEARCH_APPROVED",
    "ENSEMBLE_RESEARCH_APPROVED",
    "CHALLENGER_RETRAIN_REQUIRED",
)

FORWARD_THRESHOLDS = {
    "diagnostics": 50,
    "preliminary": 100,
    "promotion_quality": 250,
}

GBGM_FAMILY = "Gradient Boosted Goal Model"
GBGM_MODEL_ID_PREFIX = "GBGM-1"
