"""ECSE_HOME_WDE_HOME_72_RULE_FORENSIC_AND_OPTIMIZATION — read-only research."""

PROGRAM = "ECSE_HOME_WDE_HOME_72_RULE_FORENSIC_AND_OPTIMIZATION"
STATUS_COMPLETE = "ECSE_HOME_RULE_OPTIMIZATION_COMPLETE"
STATUS_NO_IMPROVEMENT = "ECSE_HOME_RULE_NO_ROBUST_IMPROVEMENT"
STATUS_DATA_LIMITED = "ECSE_HOME_RULE_DATA_LIMITED"

BASE_RULE = ("ecse_direction=home_win", "wde_decision=home_win")
TARGET_ACC = 0.75
MIN_N = 50
MIN_COVERAGE = 0.30  # of TF evaluable universe
MIN_WORST_FOLD = 0.65
MAX_LEAGUE_SHARE = 0.45
